version: '3'
services:
  app:
    container_name: oivjs-app
    build: .
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - outilsinfo_net

  db:
    container_name: oivjs-db
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - outilsinfo_net
    environment:
      - POSTGRES_DB=outilsinfo_db
      - POSTGRES_USER=outilsinfo_user
      - POSTGRES_PASSWORD=kCA$1S7*N8w9
      - PG_DATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '8001:5432'

volumes:
  db-data:

networks:
  outilsinfo_net:
