services:
  app:
    build: .
    ports:
      - '8000:80'

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backnet
    environment:
      - POSTGRES_DB=outilsinfo_db
      - POSTGRES_USER=outilsinfo_user
      - POSTGRES_PASSWORD=kCA$1S7*N8w9
    ports:
      - '8001:5432'

volumes:
  db-data:

networks:
  backnet:
