services:
  app:
    container_name: outilsinfo-app
    build: .
    ports:
      - '8080:80'
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ['python', 'app.py']

  # db:
  #   image: postgres
  #   container_name: outilsinfo-db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: outilsinfo_db
  #     POSTGRES_USER: outilsinfo_user
  #     POSTGRES_PASSWORD: outilsinfo_password
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: outilsinfo-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  pgdata:
